// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PocketParadise.Data;

#nullable disable

namespace PocketParadise.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230825201436_SeedCategoryTable")]
    partial class SeedCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.7.23375.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PocketParadise.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Halloween"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Christmas"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Valentine's Day"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Easter"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Special"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
